#!/usr/bin/env python3
from __future__ import print_function

import rospy
import odrive_ros

if __name__ == '__main__':
    try:
        odrive_ros.start_odrive()
    except rospy.ROSInterruptException:
        pass
